name: Shore House Team
favicon: null
layout_spectrum: 0.99721
typography_spectrum: 0.75372
title: New Jersey Realtors at the Shore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbd2d5'
    - '#6c081a'
    - '#220205'
    - '#ce163b'
    - '#665657'
  brandStrength: 0.3125
  lightness: 0.726634660968557
  saturation: 0.6000848112162203
  rhythmicContrast: 0.5082467428874224
purpose: []
