name: Shore House Team
favicon: null
layout_spectrum: 0.2912750383839011
typography_spectrum: 0.7261653463356197
title: New Jersey Realtors at the Shore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.02954025170765817
  lightness: 0.726634660968557
  saturation: 0.6000848112162203
  rhythmicContrast: 0.5082467428874224
purpose: []
